{
  'name':'Requiez',
  'description': 'Tema para Grupo Requiez',
  'version':'0.0.0',
  'author':'Mario Alberto Solano Zavala',
  'data': [
    'views/menu.xml',
  	'views/footer.xml',
    'views/inicio.xml',
    'views/news.xml',
    'views/transparencia.xml',
    'views/SustentabilidadCertificados.xml',
    'views/marcas.xml',
    'views/assets.xml',
    'snippets/main_requiez.xml',
    'snippets/info_main.xml',
  ],
  'category': 'Theme/Creative',
  'depends': ['website', 'web'],
} 